import { Verb } from './word.js';

export const VERBS = [
    new Verb('начинать', 'beginnen', 'begann', 'hat begonnen'),
    new Verb('предлагать', 'bieten', 'bot', 'hat geboten'),
    new Verb('просить', 'bitten', 'bat', 'hat gebeten'),
    new Verb('оставаться', 'bleiben', 'blieb', 'ist geblieben'),
    new Verb('ломать', 'brechen', 'brach', 'hat gebrochen'),
    new Verb('есть, кушать', 'essen', 'aß', 'hat gegessen'),
    new Verb('ехать', 'fahren', 'fuhr', 'ist gefahren'),
    new Verb('падать', 'fallen', 'fiel', 'ist gefallen'),
    new Verb('ловить', 'fangen', 'fing', 'hat gefangen'),
    new Verb('находить', 'finden', 'fand', 'hat gefunden'),
    new Verb('летать', 'fliegen', 'flog', 'ist geflogen'),
    new Verb('давать', 'geben', 'gab', 'hat gegeben'),
    new Verb('ходить', 'gehen', 'ging', 'ist gegangen'),
    new Verb('наслаждаться', 'genießen', 'genoss', 'hat genossen'),
    new Verb('выигрывать', 'gewinnen', 'gewann', 'hat gewonnen'),
    new Verb('держать', 'halten', 'hielt', 'hat gehalten'),
    new Verb('висеть', 'hängen', 'hing', 'hat gehangen'),
    new Verb('называться', 'heißen', 'hieß', 'hat geheißen'),
    new Verb('помогать', 'helfen', 'half', 'hat geholfen'),
    new Verb('грузить', 'laden', 'lud', 'hat geladen'),
    new Verb('позволять', 'lassen', 'ließ', 'hat gelassen'),
    new Verb('бегать', 'laufen', 'lief', 'ist gelaufen'),
    new Verb('страдать', 'leiden', 'litt', 'hat gelitten'),
    new Verb('одалживать', 'leihen', 'lieh', 'hat geliehen'),
    new Verb('читать', 'lesen', 'las', 'hat gelesen'),
    new Verb('лежать', 'liegen', 'lag', 'hat gelegen'),
    new Verb('врать', 'lügen', 'log', 'hat gelogen'),
    new Verb('брать', 'nehmen', 'nahm', 'hat genommen'),
    new Verb('приходить', 'kommen', 'kam', 'ist gekommen'),
    new Verb('нюхать', 'riechen', 'roch', 'hat gerochen'),
    new Verb('звать, кричать', 'rufen', 'rief', 'hat gerufen'),
    new Verb('делить', 'scheiden', 'schied', 'ist geschieden'),
    new Verb('спать', 'schlafen', 'schliefen', 'hat geschlafen'),
    new Verb('бить', 'schlagen', 'schlug', 'hat geschlagen'),
    new Verb('закрывать', 'schließen', 'schloss', 'geschlossen'),
    new Verb('писать', 'schreiben', 'schrieb', 'hat geschrieben'),
    new Verb('плавать', 'schwimmen', 'schwamm', 'ist geschwommen'),
    new Verb('видеть, смотреть', 'sehen', 'sah', 'gesehen'),
    new Verb('петь', 'singen', 'sang', 'hat gesungen'),
    new Verb('сидеть', 'sitzen', 'saß', 'hat gesessen'),
    new Verb('говорить', 'sprechen', 'sprach', 'hat gesprochen'),
    new Verb('стоять', 'stehen', 'stand', 'hat gestanden'),
    new Verb('воровать', 'stehlen', 'stahl', 'hat gestohlen'),
    new Verb('подниматься', 'steigen', 'stieg', 'ist gestiegen'),
    new Verb('спорить', 'streiten', 'stritt', 'hat gestritten'),
    new Verb('носить (одежду)', 'tragen', 'trug', 'hat getragen'),
    new Verb('встречать', 'treffen', 'traff', 'hat getroffen'),
    new Verb('гнать', 'treiben', 'trieb', 'ist getrieben'),
    new Verb('ступать', 'treten', 'trat', 'ist getreten'),
    new Verb('пить', 'trinken', 'trank', 'hat getrunken'),
    new Verb('делать', 'tun', 'tat', 'hat getan'),
    new Verb('забывать', 'vergessen', 'vergaß', 'hat vergessen'),
    new Verb('терять', 'verlieren', 'verlor', 'hat verloren'),
    new Verb('мыть', 'waschen', 'wusch', 'hat gewaschen'),
    new Verb('бросать', 'werfen', 'warf', 'hat geworfen'),
    new Verb('знать, уметь', 'wissen', 'wusste', 'hat gewusst'),
    new Verb('тащить', 'ziehen', 'zog', 'ist gezogen'),
];
