import { AdjectiveAdverb } from '../word.js';

export const ADJECTIVES_ADVERBS = [
    new AdjectiveAdverb('много', 'viel'),
    new AdjectiveAdverb('ветренный', 'windig'),
    new AdjectiveAdverb('прохладный', 'kühl'),
    new AdjectiveAdverb('горячий', 'heiß'),
    new AdjectiveAdverb('холодный', 'kalt'),
    new AdjectiveAdverb('разведен', 'geschieden'),
    new AdjectiveAdverb('женат, замужем', 'verheiratet'),
    new AdjectiveAdverb('один, одинокий', 'allein'),
    new AdjectiveAdverb('неправильный, неправильно', 'falsch'),
    new AdjectiveAdverb('правильный, правильно', 'richtig'),
    new AdjectiveAdverb('безработный', 'arbeitslos'),
    new AdjectiveAdverb('холостой', 'ledig'),
    new AdjectiveAdverb('готовый, готово', 'fertig'),
    new AdjectiveAdverb('больше', 'mehr'),
    new AdjectiveAdverb('солнечный', 'sonnig'),
    new AdjectiveAdverb('старый, взрослый', 'alt'),
    new AdjectiveAdverb('молодой', 'jung'),
    new AdjectiveAdverb('немецкий', 'Deutsch'),
    new AdjectiveAdverb('французский', 'Französisch'),
    new AdjectiveAdverb('итальянский', 'Italienisch'),
    new AdjectiveAdverb('испанский', 'Spanisch'),
    new AdjectiveAdverb('английский', 'Englisch'),
    new AdjectiveAdverb('русский', 'Russisch'),
    new AdjectiveAdverb('финский', 'Finnisch'),
    new AdjectiveAdverb('нидерландский', 'Niederländisch'),
    new AdjectiveAdverb('чешский', 'Tschechisch'),
    new AdjectiveAdverb('облачный', 'wolkig'),
    new AdjectiveAdverb('дождливый', 'regnerisch'),
    new AdjectiveAdverb('хороший', 'gut'),
    new AdjectiveAdverb('плохой', 'schlecht'),
    new AdjectiveAdverb('большой', 'groß'),
    new AdjectiveAdverb('маленький', 'klein'),
    new AdjectiveAdverb('дорогой', 'teuer'),
    new AdjectiveAdverb('дешевый', 'billig'),
    new AdjectiveAdverb('выгодный', 'günstig'),
    new AdjectiveAdverb('уродливый', 'hässlich'),
    new AdjectiveAdverb('длинный', 'lang'),
    new AdjectiveAdverb('хороший, красивый', 'schön'),
    new AdjectiveAdverb('легкий, простой', 'leicht'),
    new AdjectiveAdverb('короткий', 'kurz'),
    new AdjectiveAdverb('сложный, трудный', 'schwer'),
    new AdjectiveAdverb('круглый, округлый', 'rund'),
    new AdjectiveAdverb('угловатый', 'eckig'),
    new AdjectiveAdverb('черный', 'schwarz'),
    new AdjectiveAdverb('красный', 'rot'),
    new AdjectiveAdverb('желтый', 'gelb'),
    new AdjectiveAdverb('оранжевый', 'orange'),
    new AdjectiveAdverb('синий', 'blau'),
    new AdjectiveAdverb('зеленый', 'grün'),
    new AdjectiveAdverb('коричневый', 'braun'),
    new AdjectiveAdverb('белый', 'weiß'),
    new AdjectiveAdverb('пустой', 'leer'),
    new AdjectiveAdverb('узкий, тонкий', 'schmal'),
    new AdjectiveAdverb('наполовину', 'halb'),
    new AdjectiveAdverb('полный', 'voll'),
    new AdjectiveAdverb('важный', 'wichtig'),
    new AdjectiveAdverb('новый', 'neu'),
    new AdjectiveAdverb('каждый', 'jeder'),
    new AdjectiveAdverb('похожий', 'ähnlich'),
    new AdjectiveAdverb('красивый (человек)', 'hübsch'),
    new AdjectiveAdverb('симпатичный', 'sympathisch'),
    new AdjectiveAdverb('клево', 'toll'),
    new AdjectiveAdverb('комфортный', 'komfortabel'),
    new AdjectiveAdverb('приятный', 'angenehm'),
    new AdjectiveAdverb('вежливо', 'höflich'),
    new AdjectiveAdverb('невежливо', 'unhöflich'),
    new AdjectiveAdverb('вкусно', 'lecker'),
    new AdjectiveAdverb('медленно', 'langsam'),
    new AdjectiveAdverb('громко', 'laut'),
    new AdjectiveAdverb('быстро', 'schnell'),
    new AdjectiveAdverb('тихо', 'leis'),
    new AdjectiveAdverb('совсем, вполне', 'ganz'),
    new AdjectiveAdverb('добрый, милый', 'nett'),
    new AdjectiveAdverb('скучно', 'langweilig'),
    new AdjectiveAdverb('мало', 'wenig'),
    new AdjectiveAdverb('свежий', 'frisch'),
    new AdjectiveAdverb('хрустящий', 'knackig'),
    new AdjectiveAdverb('чистый', 'sauber'),
    new AdjectiveAdverb('кислый', 'sauer'),
    new AdjectiveAdverb('немного (some)', 'einige'),
    new AdjectiveAdverb('пунктуальный', 'pünktlich'),
    new AdjectiveAdverb('стройный', 'schlank'),
    new AdjectiveAdverb('просто, простой', 'einfach'),
    new AdjectiveAdverb('грандиозный, большой', 'großartig'),
    new AdjectiveAdverb('настоящий, подлинный', 'echter'),
    new AdjectiveAdverb('редкий', 'selten'),
    new AdjectiveAdverb('далекий, далеко', 'weit'),
    new AdjectiveAdverb('беременная', 'schwanger'),
    new AdjectiveAdverb('бледный', 'blass'),
    new AdjectiveAdverb('надежный, верный', 'zuverlässig'),
    new AdjectiveAdverb('опасный', 'gefährlich'),
    new AdjectiveAdverb('бесцельно, бесцельный', 'ziellos'),
    new AdjectiveAdverb('грустный', 'traurig'),
    new AdjectiveAdverb('ужасно, ужасный', 'schrecklich'),
    new AdjectiveAdverb('взволнованно, нервно, судорожно', 'aufgeregt'),
    new AdjectiveAdverb('б/у', 'gebraucht'),
    new AdjectiveAdverb('торопливо, поспешно', 'eilig'),
    new AdjectiveAdverb('жестко, крепко', 'fest'),
    new AdjectiveAdverb('прямо, просто', 'gerade'),
    new AdjectiveAdverb('случайно', 'zufällig'),
    new AdjectiveAdverb('публично', 'öffentlich'),
    new AdjectiveAdverb('незнакомый, чужой, неизвестный', 'fremd'),
    new AdjectiveAdverb('некоторый, какой-то', 'manch'),
    new AdjectiveAdverb('сильный', 'stark'),
    new AdjectiveAdverb('единственный', 'einzig'),
    new AdjectiveAdverb('взрослый, выросший', 'erwachsen'),
    new AdjectiveAdverb('рад', 'froh'),
    new AdjectiveAdverb('увлекательный', 'spannend'),
    new AdjectiveAdverb('верный, явный', 'wahr'),
    new AdjectiveAdverb('внезапно', 'plötzlich'),
    new AdjectiveAdverb('поэтому', 'deshalb'),
    new AdjectiveAdverb('вероятно', 'wahrscheinlich'),
    new AdjectiveAdverb('широкий', 'breit'),
    new AdjectiveAdverb('достаточно', 'genug'),
    new AdjectiveAdverb('любопытный', 'neugierig'),
    new AdjectiveAdverb('даже', 'sogar'),
    new AdjectiveAdverb('немедленно, тотчас', 'sofort'),
    new AdjectiveAdverb('точно, безопасно', 'sicher'),
    new AdjectiveAdverb('теперь', 'nun'),
    new AdjectiveAdverb('сообща, вместе', 'gemeinsam'),
    new AdjectiveAdverb('почти', 'fast'),
    new AdjectiveAdverb('точно', 'genau'),
    new AdjectiveAdverb('точно так же', 'genauso'),
    new AdjectiveAdverb('пестрый, красочный', 'bunt'),
    new AdjectiveAdverb('плохо, скверно', 'schlimm'),
    new AdjectiveAdverb('к тому же', 'außerdem'),
    new AdjectiveAdverb('опытный, проверенный', 'erfahren'),
    new AdjectiveAdverb('умный', 'klug'),
    new AdjectiveAdverb('светлый', 'hell'),
    new AdjectiveAdverb('крутой (наклон)', 'steil'),
    new AdjectiveAdverb('каменистый', 'steinig'),
    new AdjectiveAdverb('отчетливо', 'deutlich'),
    new AdjectiveAdverb('скудный, жидкий, худой', 'dünn'),
    new AdjectiveAdverb('несмотря на это, все же', 'trotzdem'),
    new AdjectiveAdverb('нигде', 'nirgends'),
    new AdjectiveAdverb('толстый, густой', 'dick'),
    new AdjectiveAdverb('глупый, дурной', 'dumm'),
    new AdjectiveAdverb('едва, еле-еле', 'kaum'),
    new AdjectiveAdverb('пожалуй', 'wohl'),
    new AdjectiveAdverb('в пути, в дороге', 'unterwegs'),
    new AdjectiveAdverb('наконец-то', 'endlich'),
    new AdjectiveAdverb('помешанный, "сдвинутый"', 'verrückt'),
    new AdjectiveAdverb('потом, после этого', 'danach'),
    new AdjectiveAdverb('весьма', 'ziemlich'),
    new AdjectiveAdverb('скользкий', 'glatt'),
    new AdjectiveAdverb('глубокий', 'tief'),
    new AdjectiveAdverb('иначе, в противном случае, кроме', 'sonst'),
    new AdjectiveAdverb('как минимум', 'mindestens'),
    new AdjectiveAdverb('по крайней мере, хотя бы', 'wenigstens'),
    new AdjectiveAdverb('слабый', 'schwach'),
    new AdjectiveAdverb('уставший', 'müde'),
    new AdjectiveAdverb('бодрый', 'wach'),
    new AdjectiveAdverb('мертвый', 'tot'),
    new AdjectiveAdverb('острый', 'spitz'),
    new AdjectiveAdverb('примерно, приблизительно', 'circa'),
    new AdjectiveAdverb('срочно', 'dringend'),
    new AdjectiveAdverb('то есть', 'zwar'),
    new AdjectiveAdverb('хитрый', 'listig'),
    new AdjectiveAdverb('не раздумывая', 'bedenkenlos'),
    new AdjectiveAdverb('сверхчеловеческий', 'übermenschlich'),
    new AdjectiveAdverb('постоянно', 'stets'),
    new AdjectiveAdverb('подготовленный, готовый', 'bereit'),
    new AdjectiveAdverb('почтенный', 'ehrwürdig'),
    new AdjectiveAdverb('в заключение', 'schließlich'),
    new AdjectiveAdverb('подозрительный, недоверчивый', 'argwöhnisch'),
    new AdjectiveAdverb('по случаю, иногда', 'gelegentlich'),
    new AdjectiveAdverb('скорый, быстрый', 'rasch'),
    new AdjectiveAdverb('смелый, храбрый, отважный', 'tapfer'),
    new AdjectiveAdverb('гордый', 'stolz'),
    new AdjectiveAdverb('зря', 'umsonst'),
    new AdjectiveAdverb('численный', 'zahlenmäßig'),
    new AdjectiveAdverb('превосходящий', 'überlegen'),
    new AdjectiveAdverb('определенно, решительно', 'bestimmt'),
    new AdjectiveAdverb('непобедимый', 'unbesiegbar'),
    new AdjectiveAdverb('абсолютный', 'unbedingt'),
    new AdjectiveAdverb('справедливый', 'gerecht'),
    new AdjectiveAdverb('несправедливый', 'ungerecht'),
    new AdjectiveAdverb('нетерпеливый', 'ungeduldig'),
    new AdjectiveAdverb('постепенный', 'allmählich'),
    new AdjectiveAdverb('оставшийся', 'übrig'),
    new AdjectiveAdverb('кстати', 'übrigens'),
    new AdjectiveAdverb('героический', 'heldenhaft'),
    new AdjectiveAdverb('целый, невредимый', 'heil'),
    new AdjectiveAdverb('тем временем', 'unterdessen'),
    new AdjectiveAdverb('разумный, рассудительный', 'vernünftig'),
    new AdjectiveAdverb('правый, верный', 'recht'),
    new AdjectiveAdverb('нужный, необходимый', 'nötig'),
    new AdjectiveAdverb('неуязвимый', 'unverwundbar'),
    new AdjectiveAdverb('бесполезный', 'zwecklos'),
    new AdjectiveAdverb('тем не менее, все равно', 'sowieso'),
    new AdjectiveAdverb('все равно', 'egal'),
    new AdjectiveAdverb('богатый', 'reich'),
    new AdjectiveAdverb('могучий', 'mächtig'),
    new AdjectiveAdverb('ли, если', 'ob'),
    new AdjectiveAdverb('нескучный', 'kurzweilig'),
    new AdjectiveAdverb('безобидный', 'harmlos'),
    new AdjectiveAdverb('и без того, и так уж', 'ohnehin'),
    new AdjectiveAdverb('странный, необычный', 'seltsam'),
    new AdjectiveAdverb('больной, заболевший', 'krank'),
    new AdjectiveAdverb('больно', 'weh'),
    new AdjectiveAdverb('здоровый (не больной)', 'gesund'),
    new AdjectiveAdverb('тухлый, ленивый', 'faul'),
    new AdjectiveAdverb('неловко', 'peinlich'),
    new AdjectiveAdverb('грязный', 'schmutzig'),
    new AdjectiveAdverb('ранее (как предлог)', 'vorher'),
    new AdjectiveAdverb('только, голый', 'bloß'),
];

// enn / als, bevor / ehe, bis, weil / da, damit, dass, so dass, solange, indem, wenn / falls, nachdem, während, obwohl, seit / seitdem, sooft, wohingegen

// allerdings, also, an, andererseits, anschließend, außerdem, beziehungsweise, dabei, dadurch, dafür, dagegen, damit, danach, daneben, dann, darauf, darum, darüber, darunter, dazwischen, davor, dazu, dennoch, deshalb, deswegen, einerseits, entweder, ferner, folglich, genauso, immerhin, inzwischen, jedoch, schließlich, seitdem, somit, sonst, später, trotzdem, vorher, zudem, zuerst, zuvor, weder... noch, zwar
