import { Preposition } from '../word.js';

export const PREPOSITIONS = [
    new Preposition('с, с помощью', 'mit', 'D'),
    new Preposition('куда-то, к чему-то (идти)', 'nach', 'D'),
    new Preposition('до', 'bis', 'A'),
    new Preposition('через, сквозь', 'durch', 'A'),
    new Preposition('вдоль', 'entlang', 'A'),
    new Preposition('для', 'für', 'A'),
    new Preposition('против, напротив', 'gegen', 'A'),
    new Preposition('без', 'ohne', 'A'),
    new Preposition('в (какое-то время)', 'um', 'A'),
    new Preposition('вопреки, против', 'wider', 'A'),
    new Preposition('из (откуда-то)', 'aus', 'D'),
    new Preposition('кроме, за исключением', 'außer', 'D'),
    new Preposition('у, для (работаю)', 'bei', 'D'),
    new Preposition('с (момента), на протяжении', 'seit', 'D'),
    new Preposition('из, от', 'von', 'D'),
    new Preposition('к, в (куда-то)', 'zu', 'D'),
    new Preposition('напротив, по отношению к', 'gegenüber', 'D'),
    new Preposition('с (момента)', 'ab', 'D'),
    new Preposition('на протяжении', 'während', 'G'),
    new Preposition('несмотря на, вопреки', 'trotz', 'G'),
    new Preposition('вместо', 'statt', 'G'),
    new Preposition('из-за', 'wegen', 'G'),
    new Preposition('внутри', 'innerhalb', 'G'),
    new Preposition('снаружи', 'außerhalb', 'G'),
    new Preposition('по ту сторону, вне', 'jenseits', 'G'),
    new Preposition('по эту сторону', 'diesseits', 'G'),
    new Preposition('на (вертикально), у (около)', 'an', 'AD'),
    new Preposition('на (горизонтально)', 'auf', 'AD'),
    new Preposition('за (чем-то)', 'hinter', 'AD'),
    new Preposition('в, внутри', 'in', 'AD'),
    new Preposition('рядом', 'neben', 'AD'),
    new Preposition('через, над', 'über', 'AD'),
    new Preposition('под', 'unter', 'AD'),
    new Preposition('перед', 'vor', 'AD'),
    new Preposition('между', 'zwischen', 'AD'),

    new Preposition('между', 'zwischen', 'AD'),
    new Preposition('между', 'zwischen', 'AD'),
    new Preposition('между', 'zwischen', 'AD'),
    new Preposition('между', 'zwischen', 'AD'),
    new Preposition('между', 'zwischen', 'AD'),
    new Preposition('между', 'zwischen', 'AD'),
    new Preposition('между', 'zwischen', 'AD'),
    new Preposition('между', 'zwischen', 'AD'),
    new Preposition('между', 'zwischen', 'AD'),
    new Preposition('между', 'zwischen', 'AD'),
    new Preposition('между', 'zwischen', 'AD'),
];
