import { Verb } from '../word.js';

export const VERBS = [
    new Verb('происходить', 'passieren', 'passiert', 'passierte', 'ist passiert'),
    new Verb('начинать', 'beginnen', 'beginnt', 'begann', 'hat begonnen'),
    new Verb('предоставлять, предлагать', 'bieten', 'bietet', 'bot', 'hat geboten'),
    new Verb('просить', 'bitten', 'bittet', 'bat', 'hat gebeten'),
    new Verb('оставаться', 'bleiben', 'bleibt', 'blieb', 'ist geblieben'),
    new Verb('ломать', 'brechen', 'bricht', 'brach', 'hat gebrochen'),
    new Verb('есть, кушать', 'essen', 'isst', 'aß', 'hat gegessen'),
    new Verb('ехать', 'fahren', 'fährt', 'fuhr', 'ist gefahren'),
    new Verb('падать', 'fallen', 'fällt', 'fiel', 'ist gefallen'),
    new Verb('ловить', 'fangen', 'fängt', 'fing', 'hat gefangen'),
    new Verb('находить', 'finden', 'findet', 'fand', 'hat gefunden'),
    new Verb('летать', 'fliegen', 'fliegt', 'flog', 'ist geflogen'),
    new Verb('давать', 'geben', 'gibt', 'gab', 'hat gegeben'),
    new Verb('ходить', 'gehen', 'geht', 'ging', 'ist gegangen'),
    new Verb('наслаждаться', 'genießen', 'genießt', 'genoss', 'hat genossen'),
    new Verb('выигрывать', 'gewinnen', 'gewinnt', 'gewann', 'hat gewonnen'),
    new Verb('держать, останавливаться', 'halten', 'hält', 'hielt', 'hat gehalten'),
    new Verb('висеть', 'hängen', 'hängt', 'hing', 'hat gehangen'),
    new Verb('называться', 'heißen', 'heißt', 'hieß', 'hat geheißen'),
    new Verb('помогать', 'helfen', 'hilft', 'half', 'hat geholfen'),
    new Verb('грузить', 'laden', 'lädt', 'lud', 'hat geladen'),
    new Verb('позволять', 'lassen', 'lässt', 'ließ', 'hat gelassen'),
    new Verb('бегать', 'laufen', 'läuft', 'lief', 'ist gelaufen'),
    new Verb('страдать', 'leiden', 'leidet', 'litt', 'hat gelitten'),
    new Verb('одалживать', 'leihen', 'leiht', 'lieh', 'hat geliehen'),
    new Verb('читать', 'lesen', 'liest', 'las', 'hat gelesen'),
    new Verb('лежать', 'liegen', 'liegt', 'lag', 'hat gelegen'),
    new Verb('врать', 'lügen', 'lügt', 'log', 'hat gelogen'),
    new Verb('брать', 'nehmen', 'nimmt', 'nahm', 'hat genommen'),
    new Verb('приходить', 'kommen', 'kommt', 'kam', 'ist gekommen'),
    new Verb('нюхать', 'riechen', 'riecht', 'roch', 'hat gerochen'),
    new Verb('звать, кричать', 'rufen', 'ruft', 'rief', 'hat gerufen'),
    new Verb('разлучать, разводить, сепарировать', 'scheiden', 'scheidet', 'schied', 'ist geschieden'),
    new Verb('спать', 'schlafen', 'schläft', 'schlief', 'hat geschlafen'),
    new Verb('бить', 'schlagen', 'schlägt', 'schlug', 'hat geschlagen'),
    new Verb('закрывать', 'schließen', 'schließt', 'schloss', 'geschlossen'),
    new Verb('писать', 'schreiben', 'schreibt', 'schrieb', 'hat geschrieben'),
    new Verb('плавать', 'schwimmen', 'schwimmt', 'schwamm', 'ist geschwommen'),
    new Verb('видеть, смотреть', 'sehen', 'sieht', 'sah', 'gesehen'),
    new Verb('петь', 'singen', 'singt', 'sang', 'hat gesungen'),
    new Verb('сидеть', 'sitzen', 'sitzt', 'saß', 'hat gesessen'),
    new Verb('говорить', 'sprechen', 'spricht', 'sprach', 'hat gesprochen'),
    new Verb('стоять', 'stehen', 'steht', 'stand', 'hat gestanden'),
    new Verb('воровать', 'stehlen', 'stiehlt', 'stahl', 'hat gestohlen'),
    new Verb('подниматься', 'steigen', 'steigt', 'stieg', 'ist gestiegen'),
    new Verb('спорить', 'streiten', 'streitet', 'stritt', 'hat gestritten'),
    new Verb('носить (одежду)', 'tragen', 'trägt', 'trug', 'hat getragen'),
    new Verb('встречать', 'treffen', 'trifft', 'traff', 'hat getroffen'),
    new Verb('гнать', 'treiben', 'treibt', 'trieb', 'ist getrieben'),
    new Verb('ступать', 'treten', 'tritt', 'trat', 'ist getreten'),
    new Verb('пить', 'trinken', 'trinkt', 'trank', 'hat getrunken'),
    new Verb('делать (что-то)', 'tun', 'tut', 'tat', 'hat getan'),
    new Verb('забывать', 'vergessen', 'vergisst', 'vergaß', 'hat vergessen'),
    new Verb('терять', 'verlieren', 'verliert', 'verlor', 'hat verloren'),
    new Verb('мыть', 'waschen', 'wäscht', 'wusch', 'hat gewaschen'),
    new Verb('бросать', 'werfen', 'wirft', 'warf', 'hat geworfen'),
    new Verb('знать, уметь', 'wissen', 'weiß', 'wusste', 'hat gewusst'),
    new Verb('тащить', 'ziehen', 'zieht', 'zog', 'hat gezogen'),
    new Verb('спрашивать', 'fragen', 'fragt', 'fragte', 'hat gefragt'),
    new Verb('отвечать', 'antworten', 'antwortet', 'antwortete', 'hat geantwortet'),
    new Verb('работать', 'arbeiten', 'arbeitet', 'arbeitete', 'hat gearbeitet'),
    new Verb('жить', 'wohnen', 'wohnt', 'wohnte', 'hat gewohnt'),
    new Verb('заниматься спортом', 'turnen', 'turnt', 'turnte', 'hat geturnt'),
    new Verb('играть', 'spielen', 'spielt', 'spielte', 'hat gespielt'),
    new Verb('рисовать, чертить', 'zeichnen', 'zeichnet', 'zeichnete', 'hat gezeichnet'),
    new Verb('рисовать красками', 'malen', 'malt', 'malte', 'hat gemalt'),
    new Verb('танцевать', 'tanzen', 'tanzt', 'tanzte', 'hat getanzt'),
    new Verb('слушать, слышать', 'hören', 'hört', 'hörte', 'hat gehört'),
    new Verb('учить', 'lernen', 'lernt', 'lernte', 'hat gelernt'),
    new Verb('готовить', 'kochen', 'kocht', 'kochte', 'hat gekocht'),
    new Verb('разговаривать, болтать', 'reden', 'redet', 'redete', 'hat geredet'),
    new Verb('посещать', 'besuchen', 'besucht', 'besuchte', 'hat besucht'),
    new Verb('искать', 'suchen', 'sucht', 'suchte', 'hat gesucht'),
    new Verb('верить', 'glauben', 'glaubt', 'glaubte', 'hat geglaubt'),
    new Verb('соответствовать', 'stimmen', 'stimmt', 'stimmte', 'hat gestimmt'),
    new Verb('мочь', 'können', 'kann', 'konnte', 'hat gekonnt'),
    new Verb('рассказывать', 'erzählen', 'erzählt', 'erzählte', 'hat erzählt'),
    new Verb('знать', 'kennen', 'kennt', 'kannte', 'hat gekannt'),
    new Verb('покупать', 'kaufen', 'kauft', 'kaufte', 'hat gekauft'),
    new Verb('печь, выпекать', 'backen', 'backt', 'backte', 'hat gebacken'),
    new Verb('менять', 'wechseln', 'wechselt', 'wechselte', 'ist gewechselt'),
    new Verb('заказывать', 'bestellen', 'bestellt', 'bestellte', 'hat bestellt'),
    new Verb('светить', 'scheinen', 'scheint', 'schien', 'hat geschienen'),
    new Verb('пометить крестиком', 'kreuzen', 'kreuzt', 'kreuzte', 'hat gekreuzt'),
    new Verb('делать', 'machen', 'macht', 'machte', 'hat gemacht'),
    new Verb('упорядочивать', 'ordnen', 'ordnet', 'ordnete', 'hat geordnet'),
    new Verb('сортировать', 'sortieren', 'sortiert', 'sortierte', 'hat sortiert'),
    new Verb('дополнять', 'ergänzen', 'ergänzt', 'ergänzte', 'hat ergänzt'),
    new Verb('называть по буквам', 'buchstabieren', 'buchstabiert', 'buchstabierte', 'hat buchstabiert'),
    new Verb('разрабатывать, развивать', 'entwickeln', 'entwickelt', 'entwickelte', 'hat entwickelt'),
    new Verb('жить, находиться', 'leben', 'lebt', 'lebte', 'hat gelebt'),
    new Verb('переводить (язык)', 'übersetzen', 'übersetzt', 'übersetzte', 'hat übersetzt'),
    new Verb('следить', 'achten', 'achtet', 'achtete', 'hat geachtet'),
    new Verb('соединять', 'verbinden', 'verbindet', 'verband', 'hat verbunden'),
    new Verb('связывать', 'binden', 'bindet', 'band', 'hat gebunden'),
    new Verb('подходить, быть в пору', 'passen', 'passt', 'passte', 'hat gepasst'),
    new Verb('изучать в ВУЗе', 'studieren', 'studiert', 'studierte', 'hat studiert'),
    new Verb('ставить, устанавливать, помещать', 'stellen', 'stellt', 'stellte', 'hat gestellt'),
    new Verb('платить', 'zahlen', 'zahlt', 'zahlte', 'hat gezahlt'),
    new Verb('поздравлять', 'gratulieren', 'gratuliert', 'gratulierte', 'hat gratuliert'),
    new Verb('продавать', 'verkaufen', 'verkauft', 'verkaufte', 'hat verkauft'),
    new Verb('нуждаться', 'brauchen', 'braucht', 'brauchte', 'hat gebraucht'),
    new Verb('открывать', 'öffnen', 'öffnet', 'öffnete', 'hat geöffnet'),
    new Verb('понимать', 'verstehen', 'versteht', 'verstand', 'hat verstanden'),
    new Verb('ждать', 'warten', 'wartet', 'wartete', 'hat gewartet'),
    new Verb('увольняться', 'kündigen', 'kündigt', 'kündigte', 'hat gekündigt'),
    new Verb('дождить', 'regnen', 'regnet', 'regnete', 'hat geregnet'),
    new Verb('снежить', 'schneien', 'schneit', 'schneite', 'hat geschneit'),
    new Verb('записывать', 'notieren', 'notiert', 'notierte', 'hat notiert'),
    new Verb('сравнивать', 'vergleichen', 'vergleicht', 'verglich', 'hat verglichen'),
    new Verb('представлять', 'vorstellen', 'stellt vor', 'stellte vor', 'hat vorgestellt'),
    new Verb('отрицать', 'verneinen', 'verneint', 'verneinte', 'hat verneint'),
    new Verb('вести (передачу)', 'moderieren', 'moderiert', 'moderierte', 'hat moderiert'),
    new Verb('кормить (в зоопарке)', 'füttern', 'füttert', 'fütterte', 'hat gefüttert'),
    new Verb('лаять', 'bellen', 'bellt', 'bellte', 'hat gebellt'),
    new Verb('думать, полагать', 'denken', 'denkt', 'dachte', 'hat gedacht'),
    new Verb('получать', 'bekommen', 'bekommt', 'bekam', 'hat bekommen'),
    new Verb('называть', 'nennen', 'nennt', 'nannte', 'hat genannt'),
    new Verb('хотеть, желать', 'wollen', 'will', 'wollte', 'hat gewollt'),
    new Verb('звонить (кому-то)', 'anrufen', 'ruft an', 'rief an', 'hat angerufen'),
    new Verb('торговать', 'handeln', 'handelt', 'handelte', 'hat gehandelt'),
    new Verb('рыться, выбирать (сленг)', 'stöbern', 'stöbert', 'stöberte', 'hat gestöbert'),
    new Verb('строить', 'bauen', 'baut', 'baute', 'hat gebaut'),
    new Verb('приносить', 'bringen', 'bringt', 'brachte', 'hat gebracht'),
    new Verb('мыть, убирать', 'putzen', 'putzt', 'putzte', 'hat geputzt'),
    new Verb('договариваться', 'sich verabreden', 'verabredet', 'verabredete', 'hat verabredet'),
    new Verb('просыпаться, вставать с кровати', 'aufstehen', 'steht auf', 'stand auf', 'hat aufgestanden'),
    new Verb('заканчивать', 'beenden', 'beendet', 'beendete', 'hat beendet'),
    new Verb('завтракать', 'frühstücken', 'frühstückt', 'frühstückte', 'hat gefrühstückt'),
    new Verb('бегать трусцой', 'joggen', 'joggt', 'joggte', 'hat gejoggt'),
    new Verb('гулять', 'spazieren', 'spaziert', 'spazierte', 'ist spaziert'),
    new Verb('приглашать', 'einladen', 'lädt ein', 'lud ein', 'hat eingeladen'),
    new Verb('любить, предпочитать', 'mögen', 'mag', 'mochte', 'hat gemocht'),
    new Verb('бить, стучать', 'klopfen', 'klopft', 'klopfte', 'hat geklopft'),
    new Verb('включать', 'schalten', 'schaltet', 'schaltete', 'hat geschaltet'),
    new Verb('смеяться', 'lachen', 'lacht', 'lachte', 'hat gelacht'),
    new Verb('прибираться', 'räumen', 'räumt', 'räumte', 'hat geräumt'),
    new Verb('показывать', 'zeigen', 'zeigt', 'zeigte', 'hat gezeigt'),
    new Verb('смотреть (спектакль)', 'schauen', 'schaut', 'schaute', 'hat geschaut'),
    new Verb('отправлять, посылать', 'schicken', 'schickt', 'schickte', 'hat geschickt'),
    new Verb('выбирать', 'wählen', 'wählt', 'wählte', 'hat gewählt'),
    new Verb('мечтать', 'träumen', 'träumt', 'träumte', 'hat geträumt'),
    new Verb('надевать, натягивать', 'anziehen', 'zieht an', 'zog an', 'hat angezogen'),
    new Verb('чувствовать', 'empfinden', 'empfindet', 'empfand', 'hat empfunden'),
    new Verb('улыбнуться (кому-то)', 'anstrahlen', 'strahlt an', 'strahlte an', 'hat angestrahlt'),
    new Verb('начинать (что-то)', 'anfangen', 'fängt an', 'fing an', 'hat angefangen'),
    new Verb('замечать, отмечать', 'merken', 'merkt', 'merkte', 'hat gemerkt'),
    new Verb('поворачивать, крутить', 'drehen', 'dreht', 'drehte', 'hat gedreht'),
    new Verb('желать (чего-то)', 'wünschen', 'wünscht', 'wünschte', 'hat gewünscht'),
    new Verb('резать', 'schneiden', 'schneidet', 'schnitt', 'hat geschnitten'),
    new Verb('думать, соображать', 'überlegen', 'überlegt', 'überlegte', 'hat überlegt'),
    new Verb('мямлить, бурчать', 'murmeln', 'murmelt', 'murmelte', 'hat gemurmelt'),
    new Verb('пересаживаться (транспорт)', 'umsteigen', 'steigt um', 'stieg um', 'hat umgestiegen'),
    new Verb('садиться (транспорт)', 'einsteigen', 'steigt ein', 'stieg ein', 'hat eingestiegen'),
    new Verb('выходить (транспорт)', 'aussteigen', 'steigt aus', 'stieg aus', 'hat ausgestiegen'),
    new Verb('проходить, пересекать', 'überqueren', 'überquert', 'überquerte', 'hat überquert'),
    new Verb('принадлежать', 'gehören', 'gehört', 'gehörte', 'hat gehört'),
    new Verb('иметь в виду, подразумевать', 'meinen', 'meint', 'meinte', 'hat gemeint'),
    new Verb('звенеть, звонить', 'klingeln', 'klingelt', 'klingelte', 'hat geklingelt'),
    new Verb('упаковывать', 'verpacken', 'verpackt', 'verpackte', 'hat verpackt'),
    new Verb('пробовать, пытаться', 'versuchen', 'versucht', 'versuchte', 'hat versucht'),
    new Verb('взбираться', 'klettern', 'klettert', 'kletterte', 'hat geklettert'),
    new Verb('приниматься', 'unternehmen', 'unternimmt', 'unternahm', 'hat unternommen'),
    new Verb('прибывать, приезжать', 'ankommen', 'kommt an', 'kam an', 'ist angekommen'),
    new Verb('смотреть телевизор', 'fernsehen', 'sieht fern', 'sah fern', 'hat ferngesehen'),
    new Verb('отъезжать, отправляться', 'abfahren', 'fährt ab', 'fuhr ab', 'ist abgefahren'),
    new Verb('прощаться', 'sich verabschieden', 'verabschiedet', 'verabschiedete', 'hat verabschiedet'),
    new Verb('использовать, пользоваться', 'benutzen', 'benutzt', 'benutzte', 'hat benutzt'),
    new Verb('забирать', 'abholen', 'holt ab', 'holte ab', 'hat abgeholt'),
    new Verb('подготавливать, приготавливать', 'vorbereiten', 'bereitet vor', 'bereitete vor', 'hat vorbereitet'),
    new Verb('переезжать', 'umziehen', 'zieht um', 'zog um', 'ist umgezogen'),
    new Verb('таскать', 'schleppen', 'schleppt', 'schleppte', 'hat geschleppt'),
    new Verb('тонуть', 'ertrinken', 'ertrinkt', 'ertrank', 'ist ertrunken'),
    new Verb('распространять', 'verbreiten', 'verbreitet', 'verbreitete', 'hat verbreitet'),
    new Verb('поворачивать, сворачивать', 'abbiegen', 'biegt ab', 'bog ab', 'ist abgebogen'),
    new Verb('быть одетым (во что-то), носить', 'anhaben', 'hat an', 'hatte an', 'hat angehabt'),
    new Verb('запоминать, помнить, вспоминать', 'sich erinnern', 'erinnert', 'erinnerte', 'hat erinnert'),
    new Verb('взрослеть, проистекать', 'erwachsen', 'erwächst', 'erwuchs', 'ist erwachsen'),
    new Verb('отпадать, уходить, заканчиваться', 'losgehen', 'geht los', 'ging los', 'ist losgegangen'),
    new Verb('спешить, торопиться', 'sich beeilen', 'beeilt', 'beeilte', 'hat beeilt'),
    new Verb('зарабатывать, заслуживать', 'verdienen', 'verdient', 'verdiente', 'hat verdient'),
    new Verb('выглядеть, казаться', 'aussehen', 'sieht aus', 'sah aus', 'hat ausgesehen'),
    new Verb('кивать', 'nicken', 'nickt', 'nickte', 'hat genickt'),
    new Verb('умирать', 'sterben', 'stirbt', 'starb', 'ist gestorben'),
    new Verb('предлагать', 'vorschlagen', 'schlägt vor', 'schlug vor', 'hat vorgeschlagen'),
    new Verb('ночевать, переночевать', 'übernachten', 'übernachtet', 'übernachtete', 'hat übernachtet'),
    new Verb('доставать, вытаскивать, забирать', 'holen', 'holt', 'holte', 'hat geholt'),
    new Verb('поднимать (бокал)', 'heben', 'hebt', 'hob', 'hat gehoben'),
    new Verb('повторять', 'wiederholen', 'holt wieder', 'holte wieder', 'hat wiedergeholt'),
    new Verb('тормозить, замедлять', 'bremsen', 'bremst', 'bremste', 'hat gebremst'),
    new Verb('снимать (одежду), стягивать', 'ausziehen', 'zieht aus', 'zog aus', 'hat ausgezogen'),
    new Verb('знакомиться', 'kennenlernen', 'lernt kennen', 'lernte kennen', 'hat kennengelernt'),
    new Verb('отдыхать, давать отдых', 'ausruhen', 'ruht aus', 'ruhte aus', 'hat ausgeruht'),
    new Verb('мерзнуть', 'frieren', 'friert', 'fror', 'hat gefroren'),
    new Verb('злить', 'ärgern', 'ärgert', 'ärgerte', 'hat geärgert'),
    new Verb('злиться', 'sich ärgern', 'ärgert', 'ärgerte', 'hat geärgert'),
    new Verb('пробовать на вкус, иметь вкус', 'schmecken', 'schmeckt', 'schmeckte', 'hat geschmeckt'),
    new Verb('испытывать, проверять на прочность', 'erfahren', 'erfährt', 'erfuhr', 'hat erfahren'),
    new Verb('разочаровывать, разочаровываться', 'enttäuschen', 'enttäuscht', 'enttäuschte', 'hat enttäuscht'),
    new Verb('внимательно слушать, прислушиваться, быть начеку', 'aufpassen', 'passt auf', 'passte auf', 'hat aufgepasst'),
    new Verb('будить', 'wecken', 'weckt', 'weckte', 'hat geweckt'),
    new Verb('проходить мимо, миновать', 'vorbeigehen', 'geht vorbei', 'ging vorbei', 'ist vorbeigegangen'),
    new Verb('пробуждаться, просыпаться', 'aufwachen', 'wacht auf', 'wachte auf', 'ist aufgewacht'),
    new Verb('считать (цифры)', 'zählen', 'zählt', 'zählte', 'hat gezählt'),
    new Verb('улыбаться', 'lächeln', 'lächelt', 'lächelte', 'hat gelächelt'),
    new Verb('предупреждать', 'warnen', 'warnt', 'warnte', 'hat gewarnt'),
    new Verb('трясти', 'schütteln', 'schüttelt', 'schüttelte', 'hat geschüttelt'),
    new Verb('советовать', 'raten', 'rät', 'riet', 'hat geraten'),
    new Verb('чувствовать себя', 'sich fühlen', 'fühlt', 'fühlte', 'hat gefühlt'),
    new Verb('чувствовать, испытывать', 'fühlen', 'fühlt', 'fühlte', 'hat gefühlt'),
    new Verb('вставлять, втыкать', 'stecken', 'steckt', 'steckte', 'hat gesteckt'),
    new Verb('двигаться, шевелиться', 'sich bewegen', 'bewegt', 'bewegte', 'hat bewegt'),
    new Verb('двигать, шевелить', 'bewegen', 'bewegt', 'bewegte', 'hat bewegt'),
    new Verb('обследовать, исследовать', 'untersuchen', 'untersucht', 'untersuchte', 'hat untersucht'),
    new Verb('поддерживать, развлекать', 'unterhalten', 'unterhält', 'unterhielt', 'hat unterhalten'),
    new Verb('осматриваться, оглядываться', 'umsehen', 'sieht um', 'sah um', 'hat umgesehen'),
    new Verb('ранить, повреждать', 'verletzen', 'verletzt', 'verletzte', 'hat verletzt'),
    new Verb('засыпать', 'einschlafen', 'schläft ein', 'schlief ein', 'ist eingeschlafen'),
    new Verb('запрещать', 'verbieten', 'verbietet', 'verbot', 'hat verboten'),
    new Verb('дрожать, трястись', 'zittern', 'zittert', 'zitterte', 'hat gezittert'),
    new Verb('покрывать, обматывать', 'überziehen', 'zieht über', 'zog über', 'hat übergezogen'),
    new Verb('сообщать, уведомлять', 'melden', 'meldet', 'meldete', 'hat gemeldet'),
    new Verb('длиться, продолжаться', 'dauern', 'dauert', 'dauerte', 'hat gedauert'),
    new Verb('приземляться, оказаться', 'landen', 'landet', 'landete', 'ist gelandet'),
    new Verb('разворачиваться, выворачивать', 'wenden', 'wendet', 'wandte', 'hat gewandt'),
    new Verb('светиться, сиять', 'leuchten', 'leuchtet', 'leuchtete', 'hat geleuchtet'),
    new Verb('прыгать, скакать', 'springen', 'springt', 'sprang', 'ist gesprungen'),
    new Verb('смыкаться', 'zufallen', 'fällt zu', 'fiel zu', 'ist zugefallen'),
    new Verb('собирать, коллекционировать, накапливать', 'sammeln', 'sammelt', 'sammelte', 'hat gesammelt'),
    new Verb('обещать', 'versprechen', 'verspricht', 'versprach', 'hat versprochen'),
    new Verb('улучшать', 'verbessern', 'verbessert', 'verbesserte', 'hat verbessert'),
    new Verb('ограничивать', 'beschränken', 'beschränkt', 'beschränkte', 'hat beschränkt'),
    new Verb('делить, делиться', 'teilen', 'teilt', 'teilte', 'hat geteilt'),
    new Verb('давать объявление', 'inserieren', 'inseriert', 'inserierte', 'hat inseriert'),
    new Verb('обдумывать, раздумывать', 'bedenken', 'bedenkt', 'bedachte', 'hat bedacht'),
    new Verb('доверять, доверить', 'anvertrauen', 'vertraut an', 'vertraute an', 'hat anvertraut'),
    new Verb('черпать, зачерпывать', 'schöpfen', 'schöpft', 'schöpfte', 'hat geschöpft'),
    new Verb('пережить, испытать', 'erleben', 'erlebt', 'erlebte', 'hat erlebt'),
    new Verb('находиться', 'sich befinden', 'befindet', 'befand', 'hat befunden'),
    new Verb('выть, взвывать', 'aufheulen', 'heult auf', 'heulte auf', 'hat aufgeheult'),
    new Verb('варить', 'brauen', 'braut', 'braute', 'hat gebraut'),
    new Verb('наделять, награждать', 'verleihen', 'verleiht', 'verlieh', 'hat verliehen'),
    new Verb('молчать', 'schweigen', 'schweigt', 'schwieg', 'hat geschwiegen'),
    new Verb('бояться, опасаться', 'fürchten', 'fürchtet', 'fürchtete', 'hat gefürchtet'),
    new Verb('становиться', 'werden', 'wird', 'wurde', 'ist geworden'),
    new Verb('одолеть, победить', 'besiegen', 'besiegt', 'besiegte', 'hat besiegt'),
    new Verb('производить', 'herstellen', 'stellt her', 'stellte her', 'hat hergestellt'),
    new Verb('отражать, защищаться, отбивать', 'abwehren', 'wehrt ab', 'wehrte ab', 'hat abgewehrt'),
    new Verb('занимать, оккупировать', 'besetzen', 'besetzt', 'besetzte', 'hat besetzt'),
    new Verb('совершать, выполнять', 'leisten', 'leistet', 'leistete', 'hat geleistet'),
    new Verb('окружать, опоясывать', 'umgeben', 'umgibt', 'umgab', 'hat umgeben'),
    new Verb('укреплять, фиксировать', 'befestigen', 'befestigt', 'befestigte', 'hat befestigt'),
    new Verb('практиковать, осуществлять', 'ausüben', 'übt aus', 'übte aus', 'hat ausgeübt'),
    new Verb('выполнять, доделывать', 'erledigen', 'erledigt', 'erledigte', 'hat erledigt'),
    new Verb('сидеть на корточках', 'hocken', 'hockt', 'hockte', 'hat gehockt'),
    new Verb('напугать', 'aufschrecken', 'schreckt auf', 'schreckte auf', 'hat aufgeschreckt'),
    new Verb('звучать, гласить', 'lauten', 'lautet', 'lautete', 'hat gelautet'),
    new Verb('нажимать, жать, давить', 'drücken', 'drückt', 'drückte', 'hat gedrückt'),
    new Verb('осаждать', 'belagern', 'belagert', 'belagerte', 'hat belagert'),
    new Verb('шагать', 'schreiten', 'schreitet', 'schritt', 'ist geschritten'),
    new Verb('организовывать', 'veranstalten', 'veranstaltet', 'veranstaltete', 'hat veranstaltet'),
    new Verb('определять', 'bestimmen', 'bestimmt', 'bestimmte', 'hat bestimmt'),
    new Verb('насаживать (на вертел)', 'aufspießen', 'spießt auf', 'spießte auf', 'hat aufgespießt'),
    new Verb('освободить', 'befreien', 'befreit', 'befreite', 'hat befreit'),
    new Verb('смекать, понимать', 'kapieren', 'kapiert', 'kapierte', 'hat kapiert'),
    new Verb('удалить, снять, забрать', 'abnehmen', 'nimmt ab', 'nahm ab', 'hat abgenommen'),
    new Verb('хватать', 'schnappen', 'schnappt', 'schnappte', 'ist geschnappt'),
    new Verb('разгадывать, раскусывать, видеть насквозь', 'durchblicken', 'blickt durch', 'blickte durch', 'hat durchgeblickt'),
    new Verb('течь, струиться', 'fließen', 'fließt', 'floss', 'ist geflossen'),
    new Verb('пялиться, смотреть', 'gucken', 'guckt', 'guckte', 'hat geguckt'),
    new Verb('нападать', 'angreifen', 'greift an', 'griff an', 'hat angegriffen'),
    new Verb('подметать', 'kehren', 'kehrt', 'kehrte', 'hat gekehrt'),
    new Verb('докладывать, сообщать', 'berichten', 'berichtet', 'berichtete', 'hat berichtet'),
    new Verb('вооружаться, подготавливаться', 'wappnen', 'wappnet', 'wappnete', 'hat gewappnet'),
    new Verb('запевать, затягивать', 'anstimmen', 'stimmt an', 'stimmte an', 'hat angestimmt'),
    new Verb('соглашаться, одобрять, приветствовать', 'zustimmen', 'stimmt zu', 'stimmte zu', 'hat zugestimmt'),
    new Verb('решаться, осмеливаться', 'trauen', 'traut', 'traute', 'hat getraut'),
    new Verb('кричать', 'schreien', 'schreit', 'schrie', 'hat geschrien'),
    new Verb('справляться, создавать, творить', 'schaffen', 'schafft', 'schuf', 'hat geschaffen'),
    new Verb('протягивать, хватать', 'reichen', 'reicht', 'reichte', 'hat gereicht'),
    new Verb('мчаться, бежать', 'rennen', 'rennt', 'rannte', 'hat gerannt'),
    new Verb('пытать', 'foltern', 'foltert', 'folterte', 'hat gefoltert'),
    new Verb('расстраивать, огорчать', 'bekümmern', 'bekümmert', 'bekümmerte', 'hat bekümmert'),
    new Verb('прятать', 'verstecken', 'versteckt', 'versteckte', 'hat versteckt'),
    new Verb('прятаться', 'sich verstecken', 'versteckt', 'versteckte', 'hat versteckt'),
    new Verb('вести, руководить', 'führen', 'führt', 'führte', 'hat geführt'),
    new Verb('портить, испортиться', 'verderben', 'verdirbt', 'verdarb', 'ist verdorben'),
    new Verb('принять меры', 'vorgehen', 'geht vor', 'ging vor', 'ist vorgegangen'),
    new Verb('обнаруживать, догадываться', 'rausfinden', 'findet raus', 'fand raus', 'hat rausgefunden'),
    new Verb('решать', 'entscheiden', 'entscheidet', 'entschied', 'hat entschieden'),
    new Verb('допускать, решать', 'gestatten', 'gestattet', 'gestattete', 'hat gestattet'),
    new Verb('направляться, отправляться', 'begeben', 'begibt', 'begab', 'hat begeben'),
    new Verb('веселиться, развлекать', 'amüsieren', 'amüsiert', 'amüsierte', 'hat amüsiert'),
    new Verb('скрываться, убегать', 'entkommen', 'entkommt', 'entkam', 'ist entkommen'),
    new Verb('прокрадываться', 'einschleichen', 'schleicht ein', 'schlich ein', 'hat eingeschlichen'),
    new Verb('прекращать, заканчивать', 'aufhören', 'hört auf', 'hörte auf', 'hat aufgehört'),
    new Verb('требовать', 'verlangen', 'verlangt', 'verlangte', 'hat verlangt'),
    new Verb('отменять', 'absagen', 'sagt ab', 'sagte ab', 'hat abgesagt'),
    new Verb('договариваться, согласовывать', 'vereinbaren', 'vereinbart', 'vereinbarte', 'hat vereinbart'),
    new Verb('переносить (встречу)', 'verschieben', 'verschiebt', 'verschob', 'hat verschoben'),
    new Verb('выключать', 'ausmachen', 'macht aus', 'machte aus', 'hat ausgemacht'),
    new Verb('обеспокоиться, заботиться', 'sich kümmern', 'kümmert', 'kümmerte', 'hat gekümmert'),
    new Verb('ходить под парусом, путешествовать', 'segeln', 'segelt', 'segelte', 'ist gesegelt'),
    new Verb('кашлять', 'husten', 'hustet', 'hustete', 'hat gehustet'),
    new Verb('жаловаться', 'sich beschweren', 'beschwert', 'beschwerte', 'hat beschwert'),
    new Verb('перевести (деньги)', 'überweisen', 'überweist', 'überwies', 'hat überwiesen'),
    new Verb('сопровождать, провожать', 'begleiten', 'begleitet', 'begleitete', 'hat begleitet'),
    new Verb('предсказывать, прогнозировать', 'vorhersagen', 'sagt vorher', 'sagte vorher', 'hat vorhergesagt'),
    new Verb('гладить (утюгом)', 'bügeln', 'bügelt', 'bügelte', 'hat gebügelt'),
    new Verb('пылесосить', 'staubsaugen', 'staubsaugt', 'staubsaugte', 'hat gestaubsaugt'),
    new Verb('сосать', 'saugen', 'saugt', 'saugte', 'hat gesaugt'),
    new Verb('ненавидеть, не любить', 'hassen', 'hasst', 'hasste', 'hat gehasst'),
    new Verb('открывать (более часто)', 'aufmachen', 'macht auf', 'machte auf', 'hat aufgemacht'),
    new Verb('закрывать (окно)', 'zumachen', 'macht zu', 'machte zu', 'hat zugemacht'),
    new Verb('разрешать, позволять', 'erlauben', 'erlaubt', 'erlaubte', 'hat erlaubt'),
    new Verb('купаться, принимать ванну', 'baden', 'badet', 'badete', 'hat gebadet'),
    new Verb('рыбачить', 'angeln', 'angelt', 'angelte', 'hat geangelt'),
    new Verb('сигналить', 'hupen', 'hupt', 'hupte', 'hat gehupt'),
    new Verb('двигать, надвигать', 'schieben', 'schiebt', 'schob', 'hat geschoben'),
    new Verb('рекомендовать, советовать', 'empfehlen', 'empfielt', 'empfahl', 'hat empfohlen'),
    new Verb('греметь, громыхать', 'donnern', 'donnert', 'donnerte', 'hat gedonnert'),
    new Verb('сверкать, искриться', 'blitzen', 'blitzt', 'blitzte', 'hat geblitzt'),
    new Verb('устоять, выстаивать', 'standhalten', 'hält stand', 'hielt stand', 'hat standgehalten'),
    new Verb('оценивать', 'bewerten', 'bewertet', 'bewertete', 'hat bewertet'),
    new Verb('взвешивать', 'wiegen', 'wiegt', 'wog', 'hat gewogen'),
    new Verb('провалить', 'durchfallen', 'fällt durch', 'fiel durch', 'ist durchgefallen'),
    new Verb('насыщать', 'sättigen', 'sättigt', 'sättigte', 'hat gesättigt'),
    new Verb('ругаться, браниться', 'schimpfen', 'schimpft', 'schimpfte', 'hat geschimpft'),
    new Verb('кусать', 'beißen', 'beißt', 'biss', 'hat gebissen'),
    new Verb('действовать, подействовать', 'wirken', 'wirkt', 'wirkte', 'hat gewirkt'),
    new Verb('заниматься, быть занятым', 'sich beschäftigen', 'beschäftigt', 'beschäftigte', 'hat beschäftigt'),
    new Verb('решиться', 'sich entschließen', 'entschließt', 'entschloss', 'hat entschlossen'),
    new Verb('править', 'herrschen', 'herrscht', 'herrschte', 'hat geherrscht'),
    new Verb('намереваться, собираться', 'vorhaben', 'hat vor', 'hatte vor', 'hat vorgehabt'),
    new Verb('мешать (чему-то)', 'stören', 'stört', 'störte', 'hat gestört'),
    new Verb('подать заявку', 'bewerben', 'bewirbt', 'bewarb', 'hat beworben'),
    new Verb('предлагать (синоним vorschlagen)', 'auffordern', 'fordert auf', 'forderte auf', 'hat aufgefordert'),
    new Verb('обслуживать', 'bedienen', 'bedient', 'bediente', 'hat bedient'),
    new Verb('оставлять', 'behalten', 'behält', 'behielt', 'hat behalten'),
    new Verb('получать (синоним)', 'erhalten', 'erhält', 'erhielt', 'hat erhalten'),
    new Verb('подтверждать', 'bestätigen', 'bestätigt', 'bestätigte', 'hat bestätigt'),
    new Verb('обладать', 'besitzen', 'besitzt', 'besaß', 'hat besessen'),
    new Verb('добиваться', 'erreichen', 'erreicht', 'erreichte', 'hat erreicht'),
    new Verb('завершать, заканчивать (синоним)', 'abschließen', 'schließt ab', 'schloss ab', 'hat abgeschlossen'),
    new Verb('запирать', 'absperren', 'sperrt ab', 'sperrte ab', 'hat abgesperrt'),
    new Verb('трогать, хватать', 'anfassen', 'fasst an', 'fasste an', 'hat angefasst'),
    new Verb('гореть', 'brennen', 'brennt', 'brannte', 'hat gebrannt'),
    new Verb('шить', 'nähen', 'näht', 'nähte', 'hat genäht'),
    new Verb('утверждать', 'behaupten', 'behauptet', 'behauptete', 'hat behauptet'),
    new Verb('предполагать', 'vermuten', 'vermutet', 'vermutete', 'hat vermutet'),
    new Verb('кормить (питать)', 'ernähren', 'ernährt', 'ernährte', 'hat ernährt'),
    new Verb('питаться', 'sich ernähren', 'ernährt', 'ernährte', 'hat ernährt'),
    new Verb('поправляться, оправляться', 'sich erholen', 'erholt', 'erholte', 'hat erholt'),
    new Verb('отказываться', 'sich weigern', 'weigert', 'weigerte', 'hat geweigert'),
    new Verb('стыдиться', 'sich schämen', 'schämt', 'schämte', 'hat geschämt'),
    new Verb('заниматься, иметь дело с', 'sich befassen', 'befasst', 'befasste', 'hat befasst'),
    new Verb('стараться, прилагать усилия', 'sich bemühen', 'bemüht', 'bemühte', 'hat bemüht'),
    new Verb('указывать, показывать', 'hinweisen', 'weist hin', 'wies hin', 'hat hingewiesen'),
    new Verb('присваивать, овладевать', 'sich aneignen', 'eignet an', 'eignete an', 'hat angeeignet'),
    new Verb('волноваться, переживать', 'sich aufregen', 'regt auf', 'regte auf', 'hat aufgeregt'),
    new Verb('удивлять', 'wundern', 'wundert', 'wunderte', 'hat gewundert'),
    new Verb('зависеть', 'abhängen', 'hängt ab', 'hing ab', 'hat abgehangen'),
    new Verb('теряться, заблудиться', 'sich verlaufen', 'verläuft', 'verlief', 'hat verlaufen'),
    new Verb('отсутствовать, недоставать', 'fehlen', 'fehlt', 'fehlte', 'hat gefehlt'),
    new Verb('отказаться, отклонять', 'ablehnen', 'lehnt ab', 'lehnte ab', 'hat abgelehnt'),
    new Verb('исполнять', 'erfüllen', 'erfüllt', 'erfüllte', 'hat erfüllt'),
    new Verb('случаться, происходить', 'geschehen', 'geschieht', 'geschah', 'ist geschehen'),
    new Verb('проводить (время)', 'verbringen', 'verbringt', 'verbrachte', 'hat verbracht'),
    new Verb('обижать, оскорблять', 'beleidigen', 'beleidigt', 'beleidigte', 'hat beleidigt'),
    new Verb('нырять', 'tauchen', 'taucht', 'tauchte', 'ist getaucht'),
    new Verb('потеть', 'schwitzen', 'schwitzt', 'schwitzte', 'hat geschwitzt'),
    new Verb('тратить (деньги)', 'ausgeben', 'gibt aus', 'gab aus', 'hat ausgegeben'),
    new Verb('просвящать, разъяснять', 'aufklären', 'klärt auf', 'klärte auf', 'hat aufgeklärt'),
    new Verb('принимать во внимание, иметь в виду', 'berücksichtigen', 'berücksichtigt', 'berücksichtigte', 'hat berücksichtigt'),
    new Verb('удерживать', 'festhalten', 'hält fest', 'hielt fest', 'hat festgehalten'),
    new Verb('дышать', 'atmen', 'atmet', 'atmete', 'hat geatmet'),
    new Verb('вредить', 'schaden', 'schadet', 'schadete', 'hat geschadet'),
    new Verb('проверять', 'prüfen', 'prüft', 'prüfte', 'hat geprüft'),

];
